### ISSUE TITLE
Crear categorías

### ISSUE THREAD

**Issue by Alberto-O1981** [cgkeenan/tienda#11]
Voy a añadir 3 categorias principales a la tienda: ropa, calzado y complementos. A partir de ahí se pueden añadir subcategorías como hombre y mujer y demás

**Comment by PTS28** [comment]
Por mi esta bien pero fíjate bien al crear las categorías y subcategorías

**Comment by Alberto-O1981** [comment]
Creadas 3 categorias principales y varias subcategorias
