### ISSUE TITLE
Añadir clientes

### ISSUE THREAD

**Issue by LorenzoOS11** [cgkeenan/tienda#12]
He añadido 2 clientes para ver como funcionaba y como iba la cosa

**Comment by PTS28** [comment]
vale ya vi como funciona también y parece que esta todo bien

**Comment by LorenzoOS11** [comment]
Solo añadí un par para probar como funcionaba lo añadí desde el formulario de registro propio de el PrestaShop

**Comment by PTS28** [comment]
Yo añadí uno para probar y es sencillo

**Comment by LorenzoOS11** [comment]
si es sencillo luego puedes probar que los menús de dentro de el usuario puedes añadir direcciones y tal yo añadi 2 de prueba tambien para probar y echar un vistazo a todo el menu del cliente

**Comment by PTS28** [comment]
Cierro el tema este que esta listo
