### ISSUE TITLE
Cambiar imágenes categoría ( He puesto unas temporales )

### ISSUE THREAD

**Issue by LorenzoOS11** [cgkeenan/tienda#18]

**Comment by LorenzoOS11** [comment]
He puesto unas imágenes temporales en las categorías, podéis cambiarlas sin problema era mas que nada para saber donde era el menú y quitar las que estaban por defecto

**Comment by LorenzoOS11** [comment]
Aunque yo viéndolo ahora como quedan hasta las quitaría porque quedan mal

**Comment by orangutania** [comment]
Ya las hice yo, están cargadas (sustituidas) en Archivos de Teams por las que había

**Comment by LorenzoOS11** [comment]
ok las subo ahora

**Comment by orangutania** [comment]
Genial Lorenzo, muchas gracias!
