### ISSUE TITLE
Instrucciones sobre el diseño general de la página

### ISSUE THREAD

**Issue by orangutania** [cgkeenan/tienda#19]
**Yo apostaría por una paleta de colores minimalista y sobria, Blanco y Negro, simplemente. Añadiendo color a la página con las imágenes de la ropa, complementos y zapatos, para ensalzar su visualización y una mejor experiencia de compra para el cliente sin distracciones.**

**Comment by orangutania** [comment]
<img width="427" alt="Captura de pantalla 2021-02-17 a las 12 24 39" src="https://user-images.githubusercontent.com/74956624/108197773-1e386480-711b-11eb-8932-da5f8a5fff64.png">

**Comment by PTS28** [comment]
La que sabes de esto eres tu así que decidamos todos pero si por como es la plantilla están guay esa paleta de colores

**Comment by LorenzoOS11** [comment]
Como ya visteis fui cambiando el color de los footers y el header, solo faltaría los iconos de las redes sociales, que ahora mismo no soy capaz y estoy pensando distintas maneras

**Comment by LorenzoOS11** [comment]
Si se os ocurre algo mas que retocar de la página en tema colores, tamaño o algo avisarme y lo miro

**Comment by PTS28** [comment]
Para mi esta bien así, no se si se puede cambiar el color de donde pone los descuentos pero tampoco queda mal de ese color
