### ISSUE TITLE
Proteccion de datos

### ISSUE THREAD

**Issue by Alberto-O1981** [cgkeenan/tienda#21]

**Comment by Alberto-O1981** [comment]
Creadas páginas de política de cookies y de política de privacidad

**Comment by Braisff** [comment]
en el aviso legal ya hace referencia a las cookies y en terminos y condiciones a ambas, no se si hará falta meter 2 a parte

**Comment by Braisff** [comment]
de todas formas ya hice un documento para rellenarlas al igual que con el aviso legal, pago seguro, terminos y condiciones sobre nosotros etc

**Comment by Alberto-O1981** [comment]
OK. las cierro y lo dejamos así. Además queda más limpio
