### ISSUE TITLE
Iconos de la redes sociales son funcionales y redirigen a la página principal. Hacemos cuentas fake para poner ?

### ISSUE THREAD

**Issue by LorenzoOS11** [cgkeenan/tienda#22]

**Comment by El-Wey** [comment]
Lo lógico sería hacerlos, habría que someterlo a botación, por mi no hay problema

**Comment by Alberto-O1981** [comment]
Lo suyo era crear una cuenta de correo fake, darla de alta en la tienda, crear un facebook con ella y comprobar que funciona bien

**Comment by PTS28** [comment]
Hacerlas y así por lo menos no es un botón nada más

**Comment by LorenzoOS11** [comment]
Twitter, Facebook e Inta? alguna más ?

**Comment by Braisff** [comment]
ya estan hechos por defectos solo hay que ponerles enlace a la cuenta que sea

**Comment by PTS28** [comment]
Son las principales así que yo no pondría más

**Comment by orangutania** [comment]
hago yo la de insta

**Comment by LorenzoOS11** [comment]
si lo que al poner la url de cada red social se activa el boton de la red social, lo que pasa que ahora estan redireccionando a tienda.telegal.com

**Comment by orangutania** [comment]
Cuenta: modatelegal
Contraseña: Roupar666

**Comment by LorenzoOS11** [comment]
si haceis cuenta de correo temporal avisar, y la colgais en archivos con la pass, si no ya miro yo mañana
