### ISSUE TITLE
Retoques en categorias

### ISSUE THREAD

**Issue by Alberto-O1981** [cgkeenan/tienda#23]
Como he visto el trabajo avanzado me he dedicado a retocar las categorias

**Comment by Alberto-O1981** [comment]
Añadidos meta keyswords, meta títulos, descripción y meta descripción en todas las categorías

**Comment by Alberto-O1981** [comment]
Añadidas imágenes a todas las categorías y subidas a la carpeta del teams

**Comment by Alberto-O1981** [comment]
Todos los cambios se han hecho en español y portugues

**Comment by Alberto-O1981** [comment]
Los fallos que encuentro es que me cambia el tipo de letra al cambiar el idioma (en la descripción del artículo) y no encontré como cambiarlo. Además las miniaturas de cada categoría no se pueden cambiar de tamaño (lo he intentado pero no se aprecian cambios así que las deje por defecto)

**Comment by Alberto-O1981** [comment]
Cualquier cosa me decís

**Comment by LorenzoOS11** [comment]
Yo lo estuviera mirando pero creo que quedaba mejor sin las imágenes de dentro de las categorías pero eso ya como queráis mi me da igual

**Comment by PTS28** [comment]
Yo prefiero sin las imágenes también pero como veáis

**Comment by Alberto-O1981** [comment]
Por pertición popular imágenes quitadas
