### ISSUE TITLE
Añadirse cada uno como usuarios al moodle

### ISSUE THREAD

**Issue by LorenzoOS11** [cgkeenan/tienda#26]

**Comment by PTS28** [comment]
Ya me añadí como usuario al moodle

**Comment by LorenzoOS11** [comment]
en el panel del menu de administrador busca la opcion de dar rol y metete como administrador

**Comment by orangutania** [comment]
**Hecho**

**Comment by PTS28** [comment]
Listo

**Comment by Roupares** [comment]
Ya estoy añadido al moodle con usuario y ademas rol administrador xd
