### ISSUE TITLE
Selección de color para el moodle

### ISSUE THREAD

**Issue by LorenzoOS11** [cgkeenan/tienda#28]

**Comment by LorenzoOS11** [comment]
¿Que paleta de colores preferís en el moodle?

**Comment by PTS28** [comment]
Azul no esta mal pero el problema es que en la parte de los cursos la letra te la pone en azul, prueba con verde, azul más claro, violeta. Con que no sea muy cantoso debería valer

**Comment by PTS28** [comment]
Un color más claro, si te fijas en la rueda de las opciones sale un poco oscuro demás el menú

**Comment by LorenzoOS11** [comment]
ok

**Comment by PTS28** [comment]
Se puede poner la letra en negrita o más oscura?

**Comment by LorenzoOS11** [comment]
creo que si ahora pruebo, incluso un poco mas de tamaño de letra

**Comment by LorenzoOS11** [comment]
¿ mejor ahora ?

**Comment by PTS28** [comment]
si, así mejor

**Comment by PTS28** [comment]
![Captura](https://user-images.githubusercontent.com/74956689/108841549-3c4d0b80-75d8-11eb-9fda-86694dea5b25.PNG)
Se le puede poner algo más fuerte la letra?

**Comment by Roupares** [comment]
En cursos disponibles las letras guay ;)

**Comment by Roupares** [comment]
no se si le pones un color marrón o algo asi podrian quedar guay, pero no se que opinara el resto

**Comment by PTS28** [comment]
Como veáis

**Comment by LorenzoOS11** [comment]
listo, la puse en letra negra y negrita a mayores, el problema es que si el marrón es muy claro le va a pasar lo mismo que como estaba antes, y si es muy oscuro es igual que el negro xD

**Comment by PTS28** [comment]
Yo creo que esta bien así pero como queráis la mayoría

**Comment by orangutania** [comment]
Yo lo veo bien así, cómo se llama el centro formativo? para hacer el logotipo

**Comment by LorenzoOS11** [comment]
hazlo con el nombre de moodlegal mismo

**Comment by orangutania** [comment]
ok, estoy en ello
