### ISSUE TITLE
Últimos retoques

### ISSUE THREAD

**Issue by LorenzoOS11** [cgkeenan/tienda#33]

**Comment by LorenzoOS11** [comment]
Ya pocas cosas se me ocurren de ir tocando, quedaría algo sobre permisos / roles / dejar que los invitados entren a algún curso.
Mas que nada echarle un vistazo por encima, yo acabo de instalar lo de las videollamadas y si se me ocurre algo más lo iré metiendo.

**Comment by graceylu** [comment]
ya está capturado todo ahora lo subo a los archivos ,no me dejó cambiar la apariencia en la app porque es la version mas sencilla la gratuita ,se puede entrar con moodlegal  sin problema.
