### ISSUE TITLE
Decisiones a tomar - Artículos

### ISSUE THREAD

**Issue by cgkeenan** [cgkeenan/tienda#5]
2.- Tipo de cobro de los artículos

**Comment by cgkeenan** [comment]
A decidir en función de la instalación del Prestashop.

**Comment by PTS28** [comment]
Voy a empezar a mirar como funciona el tema de las descripciones de los productos con los ejemplos de las dos camisetas que ya vienen predefinidas en la plantilla

**Comment by PTS28** [comment]
Modifique los ejemplos para saber como funciona y es bastante fácil, son menús muy sencillos

**Comment by PTS28** [comment]
Voy añadir 3 de ropa para hombre y 3 de ropa para mujer, añadir vosotros las otras categorías los productos si queréis

**Comment by PTS28** [comment]
Ya metí todos los artículos en cada categoría, si queréis cambiar alguna descripción o algo sois libres de cambiar lo que queráis. Cierro este tema ya?
